In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("credit_scoring - credit_scoring.csv")

In [3]:
df.head()

,Age,Gender,Marital Status,Education Level,Employment Status,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term,Type of Loan
0,60,Male,Married,Master,Employed,0.22,2685,2,4675000,2.65,48,Personal Loan
1,25,Male,Married,High School,Unemployed,0.20,2371,9,3619000,5.19,60,Auto Loan
2,30,Female,Single,Master,Employed,0.22,2771,6,957000,2.76,12,Auto Loan
3,58,Female,Married,PhD,Unemployed,0.12,1371,2,4731000,6.57,60,Auto Loan
4,32,Male,Married,Bachelor,Self-Employed,0.99,828,2,3289000,6.28,36,Personal Loan

In [14]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [8]:
np.round(df.describe(),2)

,Age,Credit Utilization Ratio,Payment History,Number of Credit Accounts,Loan Amount,Interest Rate,Loan Term
count,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00
mean,42.70,0.51,1452.81,5.58,2471401.00,10.69,37.13
std,13.27,0.29,827.93,2.93,1387046.68,5.48,17.44
min,20.00,0.00,0.00,1.00,108000.00,1.01,12.00
25%,31.00,0.25,763.75,3.00,1298000.00,6.02,24.00
50%,42.00,0.53,1428.00,6.00,2437500.00,10.70,36.00
75%,54.00,0.75,2142.00,8.00,3653250.00,15.44,48.00
max,65.00,1.00,2857.00,10.00,4996000.00,19.99,60.00

In [16]:
df.shape

(1000, 12)

In [6]:
x_train=df.drop(columns=['Number of Credit Accounts'])
y_train=df["Number of Credit Accounts"]

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [28]:
num_col=df['Age', 'Credit Utilization Ratio', 'Loan Amount', 'Interest Rate', 'Loan Term', 'Payment History', 'Number of Credit Accounts']

KeyError: ('Age', 'Credit Utilization Ratio', 'Loan Amount', 'Interest Rate', 'Loan Term', 'Payment History', 'Number of Credit Accounts')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Age                        1000 non-null   int64
 1   Gender                     1000 non-null   object
 2   Marital Status             1000 non-null   object
 3   Education Level            1000 non-null   object
 4   Employment Status          1000 non-null   object
 5   Credit Utilization Ratio   1000 non-null   float64
 6   Payment History            1000 non-null   int64
 7   Number of Credit Accounts  1000 non-null   int64
 8   Loan Amount                1000 non-null   int64
 9   Interest Rate              1000 non-null   float64
 10  Loan Term                  1000 non-null   int64
 11  Type of Loan               1000 non-null   object
dtypes: float64(2), int64(5), object(5)
memory usage: 93.9+ KB

In [25]:
cat_col=df['Gender', 'Marital Status', 'Education Level', 
       'Employment Status', 'Type of Loan']

In [26]:
transformer=ColumnTransformer(transformers=[
    
    ("num",StandardScaler(),num_col),

    ("tnf3",OneHotEncoder(sparse_output=False,drop="first"),cat_col)

    
    
],remainder="passthrough")

In [27]:
transformer.fit_transform(x_train).shape

ValueError: No valid specification of the columns. Only a scalar, list or slice of all integers or all strings, or boolean mask is allowed